### ISSUE TITLE
Error in demo code (table editing)

### ISSUE THREAD

**Issue by uniconstructor** [mesqueeb/quasar-ui-easy-tables#4]
Hi there. Great plugin! 
I found an error in demo page: https://quasar-easy-tables.web.app/editing

Please replace 'rowData' to formData insecond example (editable form on button click):
![easy-table-error-screen](https://user-images.githubusercontent.com/1384545/75838732-cacce980-5dd7-11ea-9964-8ae1aac7ca8f.png)

**Comment by mesqueeb** [comment]
@uniconstructor oh nice catch!!!
I really have to improve the way I'm rendering the example source code a bit. : S

Thanks for reporting, I'll get to this soonish 😛

**Comment by mesqueeb** [comment]
@uniconstructor I completely fixed up the docs!! See #16
