### ISSUE TITLE
The plugin is great, but i don't know how to make serverside pagination

### ISSUE THREAD

**Issue by isbincApps** [mesqueeb/quasar-ui-easy-tables#6]

**Comment by mesqueeb** [comment]
Thanks for your issue!
However, I'm afraid that's out of the scope of this project.

You can fork my project, and implement it directly into the main table component:
https://github.com/mesqueeb/quasar-ui-easy-tables/blob/master/ui/src/components/EasyTable.vue

Or you could use Quasar tables instead. They have a guide on this:
https://quasar.dev/vue-components/table#Server-side-pagination%2C-filter-and-sorting

**Comment by isbincApps** [comment]
ok @mesqueeb, thanks
