### ISSUE TITLE
Add support for id as Number in table rows

### ISSUE THREAD

**Issue by cabassi** [mesqueeb/quasar-ui-easy-tables#9]
vue.runtime.esm.js?2b0e:619 [Vue warn]: Invalid prop: type check failed for prop "id". Expected String with value "1", got Number with value 1.

found in

---> <EasyRow>

When using id as a field in the table rows, the above error is thrown to the console. In my model ID is a Number, but it seems that the plugin is using the id field for other things rather than just displaying it as a normal column.

**Comment by mesqueeb** [comment]
@cabassi I don't think I will implement this. But I just finished rewriting the entire library as Blitzar!

See #16

feel free to open new issues over there, I might reconsider
